name: train_and_evaluate

on:
  workflow_dispatch:
    inputs:
      hidden_size:
        description: 'Hidden size of the model'
        required: true
        default: '128'
      learning_rate:
        description: 'Learning rate of the model'
        required: true
        default: '0.001'
      weight_decay:
        description: 'Weight decay of the model'
        required: true
        default: '0.001'
      epochs:
        description: 'Number of epochs'
        required: true
        default: '1000'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get data
        uses: actions/upload-artifact@v2
        with:
          name: datasets
          path: datasets/**

  train:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download data
        uses: actions/download-artifact@v2
        with:
          name: datasets

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python create_model.py --hidden_size ${{ github.event.inputs.hidden_size }} --learning_rate ${{ github.event.inputs.learning_rate }} --weight_decay ${{ github.event.inputs.weight_decay }} --epochs ${{ github.event.inputs.epochs }}

      - name: Upload model
        uses: actions/upload-artifact@v2
        with:
          name: model
          path: models/model.pth

  evaluate:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get model
        uses: actions/download-artifact@v2
        with:
          name: model
          path: models

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Evaluate
        run: |
          python predict.py